### ISSUE TITLE
Fix broken tests due to usage of bitstring.Bits in encode wrappers

### ISSUE THREAD

**Issue by ekzyis** [ekzyis/cryptography#26]
#25

**Comment by ekzyis** [comment]
```
.E...E...............................................s.ss.s............................E.......................................................
======================================================================
ERROR: test_integration_feal_encrypt_all_options_combined (test.ciphers.feal.integration.test_feal_all_options_combined.TestFEALAllOptionsCombined)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/mock.py", line 1348, in patched
    return func(*newargs, **newkeywargs)
  File "/home/ekzyis/Dokumente/Studium/thesis/repo/test/ciphers/sysv_patcher.py", line 20, in wrapper
    return fn(*unittest_args)
  File "/home/ekzyis/Dokumente/Studium/thesis/repo/test/ciphers/feal/integration/test_feal_all_options_combined.py", line 12, in test_integration_feal_encrypt_all_options_combined
    c = feal()
  File "/home/ekzyis/Dokumente/Studium/thesis/repo/test/../src/ciphers/block/feal.py", line 247, in feal
    return _encrypt(k, text, n=n)
  File "/home/ekzyis/Dokumente/Studium/thesis/repo/test/../src/ciphers/modi/wrap.py", line 153, in cipher_fn_wrapper
    return formatter(cipher_fn(key, text, *args, **kwargs))
  File "/home/ekzyis/Dokumente/Studium/thesis/repo/test/../src/ciphers/block/../../util/encode.py", line 31, in cipher_fn_wrapper
    return cipher_fn(key, encode(text), *args, **kwargs)
  File "/home/ekzyis/Dokumente/Studium/thesis/repo/test/../src/ciphers/modi/ecb.py", line 29, in _ecb
    n = ceil(text.bit_length() / blocksize)
AttributeError: 'Bits' object has no attribute 'bit_length'

======================================================================
ERROR: test_integration_feal_encrypt_encoding_utf8 (test.ciphers.feal.integration.test_feal_option_encoding.TestFEALOptionEncoding)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/mock.py", line 1348, in patched
    return func(*newargs, **newkeywargs)
  File "/home/ekzyis/Dokumente/Studium/thesis/repo/test/ciphers/sysv_patcher.py", line 20, in wrapper
    return fn(*unittest_args)
  File "/home/ekzyis/Dokumente/Studium/thesis/repo/test/ciphers/feal/integration/test_feal_option_encoding.py", line 13, in test_integration_feal_encrypt_encoding_utf8
    c = feal()
  File "/home/ekzyis/Dokumente/Studium/thesis/repo/test/../src/ciphers/block/feal.py", line 247, in feal
    return _encrypt(k, text, n=n)
  File "/home/ekzyis/Dokumente/Studium/thesis/repo/test/../src/ciphers/modi/wrap.py", line 153, in cipher_fn_wrapper
    return formatter(cipher_fn(key, text, *args, **kwargs))
  File "/home/ekzyis/Dokumente/Studium/thesis/repo/test/../src/ciphers/block/../../util/encode.py", line 31, in cipher_fn_wrapper
    return cipher_fn(key, encode(text), *args, **kwargs)
  File "/home/ekzyis/Dokumente/Studium/thesis/repo/test/../src/ciphers/block/feal.py", line 191, in encrypt
    raise ValueError("Plaintext must be a number")
ValueError: Plaintext must be a number

======================================================================
ERROR: test_ecb_with_encode_wrapper (test.integration.test_options_wrapping.TestOptionsWrapping)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ekzyis/Dokumente/Studium/thesis/repo/test/integration/test_options_wrapping.py", line 14, in test_ecb_with_encode_wrapper
    o = encode_wrapper(ecb_wrap)(k, m)
  File "/home/ekzyis/Dokumente/Studium/thesis/repo/test/../src/ciphers/block/../../util/encode.py", line 31, in cipher_fn_wrapper
    return cipher_fn(key, encode(text), *args, **kwargs)
  File "/usr/lib/python3.8/unittest/mock.py", line 1081, in __call__
    return self._mock_call(*args, **kwargs)
  File "/usr/lib/python3.8/unittest/mock.py", line 1085, in _mock_call
    return self._execute_mock_call(*args, **kwargs)
  File "/usr/lib/python3.8/unittest/mock.py", line 1155, in _execute_mock_call
    return self._mock_wraps(*args, **kwargs)
  File "/home/ekzyis/Dokumente/Studium/thesis/repo/test/../src/ciphers/modi/ecb.py", line 29, in _ecb
    n = ceil(text.bit_length() / blocksize)
AttributeError: 'Bits' object has no attribute 'bit_length'

----------------------------------------------------------------------
Ran 143 tests in 7.262s

FAILED (errors=3, skipped=4)
```
