### ISSUE TITLE
ChaCha Hash Tests fail for DJB version with counter != 0

### ISSUE THREAD

**Issue by ekzyis** [ekzyis/cryptography#40]
```
$> python -m unittest -k test_chacha_chacha_hash -v
test_chacha_chacha_hash_DJB_1_counter_0 (test.ciphers.chacha.test_chacha_chacha_hash.TestChaChaChaChaHash)
Test #1 for ChaCha Block function DJB version with 64-bit nonce and 64-bit counter set to 0.

        TC1: All zero key and IV.

        Key:        00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
        Nonce:      00:00:00:00:00:00:00:00
        Counter:    00:00:00:00:00:00:00:00
         ... ok
test_chacha_chacha_hash_DJB_1_counter_1 (test.ciphers.chacha.test_chacha_chacha_hash.TestChaChaChaChaHash)
Test #1 for ChaCha Block function DJB version with 64-bit nonce and 64-bit counter set to 1.

        TC1: All zero key and IV.

        Key:        00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
        Nonce:      00:00:00:00:00:00:00:00
        Counter:    00:00:00:00:00:00:00:01
         ... FAIL
test_chacha_chacha_hash_DJB_2_counter_0 (test.ciphers.chacha.test_chacha_chacha_hash.TestChaChaChaChaHash)
Test #2 for ChaCha Block function DJB version with 64-bit nonce and 64-bit counter set to 0.

        TC2: Single bit in key set. All zero IV.

        Key:        01:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
        Nonce:      00:00:00:00:00:00:00:00
        Counter:    00:00:00:00:00:00:00:00
         ... ok
test_chacha_chacha_hash_DJB_2_counter_1 (test.ciphers.chacha.test_chacha_chacha_hash.TestChaChaChaChaHash)
Test #2 for ChaCha Block function DJB version with 64-bit nonce and 64-bit counter set to 1.

        TC2: Single bit in key set. All zero IV.

        Key:        01:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
        Nonce:      00:00:00:00:00:00:00:00
        Counter:    00:00:00:00:00:00:00:01
         ... FAIL
test_chacha_chacha_hash_DJB_random_key_and_iv_counter_0 (test.ciphers.chacha.test_chacha_chacha_hash.TestChaChaChaChaHash)
Test #3 for ChaCha Block Function DJB version with 64-bit nonce and 64-bit counter set 0.

        TC8: Random key and IV.

        Key:        c4:6e:c1:b1:8c:e8:a8:78:72:5a:37:e7:80:df:b7:35:1f:68:ed:2e:19:4c:79:fb:c6:ae:be:e1:a6:67:97:5d
        Nonce:      1a:da:31:d5:cf:68:82:21
        Counter:    00:00:00:00:00:00:00:00
         ... ok
test_chacha_chacha_hash_DJB_random_key_and_iv_counter_1 (test.ciphers.chacha.test_chacha_chacha_hash.TestChaChaChaChaHash)
Test #3 for ChaCha Block Function DJB version with 64-bit nonce and 64-bit counter set 1.

        TC8: Random key and IV.

        Key:        c4:6e:c1:b1:8c:e8:a8:78:72:5a:37:e7:80:df:b7:35:1f:68:ed:2e:19:4c:79:fb:c6:ae:be:e1:a6:67:97:5d
        Nonce:      1a:da:31:d5:cf:68:82:21
        Counter:    00:00:00:00:00:00:00:01
         ... FAIL
test_chacha_chacha_hash_IETF_1_counter_1 (test.ciphers.chacha.test_chacha_chacha_hash.TestChaChaChaChaHash)
Test for ChaCha Block Function IETF version with 96-bit nonce and 32-bit counter.

        Key:        00:01:02:03:04:05:06:07:08:09:0a:0b:0c:0d:0e:0f:10:11:12:13:14:15:16:17:18:19:1a:1b:1c:1d:1e:1f
        Nonce:      00:00:00:09:00:00:00:4a:00:00:00:00
        Counter:    00:00:00:01
         ... ok

======================================================================
FAIL: test_chacha_chacha_hash_DJB_1_counter_1 (test.ciphers.chacha.test_chacha_chacha_hash.TestChaChaChaChaHash)
Test #1 for ChaCha Block function DJB version with 64-bit nonce and 64-bit counter set to 1.

        TC1: All zero key and IV.

        Key:        00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
        Nonce:      00:00:00:00:00:00:00:00
        Counter:    00:00:00:00:00:00:00:01
        
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ekzyis/Dokumente/Studium/thesis/repo/test/ciphers/chacha/test_chacha_chacha_hash.py", line 86, in test_chacha_chacha_hash_DJB_1_counter_1
    self.assertEqual(
AssertionError: Bits('0x3db41d3aa0d329285de6f225e6e24bd59c9a17006[84 chars]b5a') != Bits('0x9f07e7be5551387a98ba977c732d080dcb0f29a04[84 chars]d6f')

======================================================================
FAIL: test_chacha_chacha_hash_DJB_2_counter_1 (test.ciphers.chacha.test_chacha_chacha_hash.TestChaChaChaChaHash)
Test #2 for ChaCha Block function DJB version with 64-bit nonce and 64-bit counter set to 1.

        TC2: Single bit in key set. All zero IV.

        Key:        01:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
        Nonce:      00:00:00:00:00:00:00:00
        Counter:    00:00:00:00:00:00:00:01
        
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ekzyis/Dokumente/Studium/thesis/repo/test/ciphers/chacha/test_chacha_chacha_hash.py", line 150, in test_chacha_chacha_hash_DJB_2_counter_1
    self.assertEqual(
AssertionError: Bits('0xc0bf10c0fefcc6f4c8ece615ec18443565fedc018[84 chars]9a2') != Bits('0x10f656e6d1fd55053e50c4875c9930a33f6d0263b[84 chars]eac')

======================================================================
FAIL: test_chacha_chacha_hash_DJB_random_key_and_iv_counter_1 (test.ciphers.chacha.test_chacha_chacha_hash.TestChaChaChaChaHash)
Test #3 for ChaCha Block Function DJB version with 64-bit nonce and 64-bit counter set 1.

        TC8: Random key and IV.

        Key:        c4:6e:c1:b1:8c:e8:a8:78:72:5a:37:e7:80:df:b7:35:1f:68:ed:2e:19:4c:79:fb:c6:ae:be:e1:a6:67:97:5d
        Nonce:      1a:da:31:d5:cf:68:82:21
        Counter:    00:00:00:00:00:00:00:01
        
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ekzyis/Dokumente/Studium/thesis/repo/test/ciphers/chacha/test_chacha_chacha_hash.py", line 214, in test_chacha_chacha_hash_DJB_random_key_and_iv_counter_1
    self.assertEqual(
AssertionError: Bits('0x94fbbd512f9fb96721957f4a3723cfa2cf6175c85[84 chars]014') != Bits('0xe5fbc34e60a1d9a9db17345b0a402736853bf910b[84 chars]332')

----------------------------------------------------------------------
Ran 7 tests in 0.600s

FAILED (failures=3)
```

**Comment by ekzyis** [comment]
I will use `test_chacha_chacha_hash_DJB_1_counter_1` as a reference for successful counter encoding; meaning that I assume that if I can make this test pass, the others failing tests will most likely also succeed.

Test case description:

`test_chacha_chacha_hash_DJB_1_counter_1`
```
Test #1 for ChaCha Block function DJB version with 64-bit nonce and 64-bit counter set to 1.

TC1: All zero key and IV.

Key:        00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
Nonce:      00:00:00:00:00:00:00:00
Counter:    1
```
I have tried following counter encodings:

- 00:00:00:00:00:00:00:01 as `bitseq64(0x1)`
- 01:00:00:00:00:00:00:00 as `bitseq64(0x1, (0x0,) * 7)`

... and while writing this I tested 

- 00:00:00:01:00:00:00:00 as `bitseq8((0x0,) * 3, 0x1, (0x0,) * 4)`

and it succeeded!

**Comment by ekzyis** [comment]
The following piece of code did transform the counter into chunks of 4 byte and then formatted it as little-endian:

```python
counter = bitseq64(0x1)
print(counter)
print(*bitseq_split(32, counter, formatter=littleendian))
```
Output:
```
00:00:00:00:00:00:00:01
00:00:00:00 01:00:00:00
```

As one can see, this is **not** the same as 00:00:00:01:00:00:00:00.

`bitseq_split` first splits the bitstring and then runs the formatter on each chunk.

What is needed for the correct encoding would be to first format the bitstring as little-endian, split it into 4 byte chunks and the format each chunk again as little-endian:

0. 00:00:00:00 00:00:00:01 (initial value of counter)
1. 01:00:00:00:00:00:00:00 (as little-endian)
2. 01:00:00:00 00:00:00:00 (as 4 byte chunks)
3. 00:00:00:01 00:00:00:00 (each chunk as little-endian)
